/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import entities._Account;

/**
 *
 * @author ICHIGEKI
 */
public class FAdmin extends javax.swing.JFrame {

    /**
     * Creates new form FAdmin
     */
    public FAdmin() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnRoomManage = new javax.swing.JButton();
        btnServiceManage = new javax.swing.JButton();
        btnEmployeeManage = new javax.swing.JButton();
        btnChangePass = new javax.swing.JButton();
        btnAccountManage = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(0, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/banner_Admin.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btnRoomManage.setBackground(new java.awt.Color(51, 51, 255));
        btnRoomManage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/btnRoomMana.png"))); // NOI18N
        btnRoomManage.setMaximumSize(new java.awt.Dimension(230, 100));
        btnRoomManage.setMinimumSize(new java.awt.Dimension(230, 100));
        btnRoomManage.setPreferredSize(new java.awt.Dimension(230, 100));
        btnRoomManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRoomManageActionPerformed(evt);
            }
        });

        btnServiceManage.setBackground(new java.awt.Color(153, 0, 153));
        btnServiceManage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/btnServiceManage.png"))); // NOI18N
        btnServiceManage.setMaximumSize(new java.awt.Dimension(230, 100));
        btnServiceManage.setMinimumSize(new java.awt.Dimension(230, 100));
        btnServiceManage.setPreferredSize(new java.awt.Dimension(230, 100));
        btnServiceManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServiceManageActionPerformed(evt);
            }
        });

        btnEmployeeManage.setBackground(new java.awt.Color(204, 0, 0));
        btnEmployeeManage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/btnEmployeeMana.png"))); // NOI18N
        btnEmployeeManage.setMaximumSize(new java.awt.Dimension(230, 100));
        btnEmployeeManage.setMinimumSize(new java.awt.Dimension(230, 100));
        btnEmployeeManage.setPreferredSize(new java.awt.Dimension(230, 100));
        btnEmployeeManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeManageActionPerformed(evt);
            }
        });

        btnChangePass.setBackground(new java.awt.Color(0, 0, 153));
        btnChangePass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/btnChangePass.png"))); // NOI18N
        btnChangePass.setMaximumSize(new java.awt.Dimension(230, 100));
        btnChangePass.setMinimumSize(new java.awt.Dimension(230, 100));
        btnChangePass.setPreferredSize(new java.awt.Dimension(230, 100));
        btnChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePassActionPerformed(evt);
            }
        });

        btnAccountManage.setBackground(new java.awt.Color(204, 102, 0));
        btnAccountManage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/btnAccMana.png"))); // NOI18N
        btnAccountManage.setMaximumSize(new java.awt.Dimension(230, 100));
        btnAccountManage.setMinimumSize(new java.awt.Dimension(230, 100));
        btnAccountManage.setPreferredSize(new java.awt.Dimension(230, 100));
        btnAccountManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountManageActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(0, 0, 153));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/btnLogout.png"))); // NOI18N
        btnLogout.setMaximumSize(new java.awt.Dimension(230, 100));
        btnLogout.setMinimumSize(new java.awt.Dimension(230, 100));
        btnLogout.setPreferredSize(new java.awt.Dimension(230, 100));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAccountManage, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRoomManage, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnServiceManage, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEmployeeManage, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnChangePass, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnServiceManage, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRoomManage, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEmployeeManage, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChangePass, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAccountManage, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRoomManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoomManageActionPerformed
        FARoom aa = new FARoom();
        aa.setAccount(acc);
        aa.setLocationRelativeTo(this);
        aa.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRoomManageActionPerformed

    private void btnServiceManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServiceManageActionPerformed
        FAService r = new FAService();
        r.setAccount(acc);
        r.setLocationRelativeTo(this);
        r.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnServiceManageActionPerformed

    private void btnEmployeeManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeManageActionPerformed
        FAEmployee ff = new FAEmployee();
        ff.setAccount(acc);
        ff.setLocationRelativeTo(this);
        ff.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEmployeeManageActionPerformed

    private void btnAccountManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountManageActionPerformed
        FAAccount acc = new FAAccount();
        acc.setAccount(this.acc);
        acc.setLocationRelativeTo(this);
        acc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAccountManageActionPerformed

    private void btnChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePassActionPerformed
        FChangePass change = new FChangePass(acc.getUserName());
        change.setAccount(acc);
        change.setLocationRelativeTo(this);
        change.setVisible(true);
    }//GEN-LAST:event_btnChangePassActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        FLogin logout = new FLogin();
        logout.setLocationRelativeTo(this);
        logout.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FAdmin().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccountManage;
    private javax.swing.JButton btnChangePass;
    private javax.swing.JButton btnEmployeeManage;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRoomManage;
    private javax.swing.JButton btnServiceManage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
    _Account acc = new _Account();

    public void setAccount(_Account aa) {
        acc = aa;
    }
}
